# Generated by Django 5.1.1 on 2024-10-09 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
