# Generated by Django 5.1.1 on 2024-10-11 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
