# Generated by Django 5.1.1 on 2024-10-07 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_quantity', models.PositiveIntegerField()),
                ('total_left', models.PositiveIntegerField()),
                ('dosage_per_intake', models.PositiveIntegerField()),
                ('frequency_per_day', models.PositiveIntegerField()),
                ('time_interval', models.PositiveIntegerField()),
                ('last_intake_time', models.DateTimeField(blank=True, null=True)),
                ('priority_flag', models.BooleanField(default=False)),
                ('priority_lead_time', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('exhausted', 'Exhausted'), ('missed', 'Missed')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
