# Generated by Django 5.1.1 on 2024-10-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('exhausted', 'Exhausted'), ('missed', 'Missed'), ('stopped', 'Stopped'), ('deleted', 'Deleted')], default='active', max_length=50),
        ),
    ]
