# Generated by Django 5.1.1 on 2024-10-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_alter_medication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='time_interval',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
