# Generated by Django 5.1.1 on 2024-10-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_alter_medication_time_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('taken', 'Taken'), ('missed', 'Missed'), ('completed', 'Completed')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='medication',
            name='total_left',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
