# Generated by Django 5.1.1 on 2024-10-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0005_alter_medication_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='name',
            new_name='drug_name',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='time_interval',
        ),
        migrations.AlterField(
            model_name='medication',
            name='frequency_per_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
