# Generated by Django 5.1.1 on 2024-10-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0006_rename_name_medication_drug_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='last_intake_time',
        ),
        migrations.AddField(
            model_name='medication',
            name='time_interval',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
