# Generated by Django 5.1.1 on 2024-10-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0007_remove_medication_last_intake_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='last_intake_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
