# Generated by Django 5.1.1 on 2024-10-10 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0008_medication_last_intake_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='last_intake_time',
            new_name='last_scheduled_time',
        ),
    ]
