# Generated by Django 5.1.1 on 2024-10-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='next_dose',
            new_name='next_dose_schedule',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('fulfilled', 'Fulfilled'), ('missed', 'Missed'), ('stopped', 'Stopped'), ('deleted', 'Deleted')], default='scheduled', max_length=50),
        ),
    ]
