# Generated by Django 5.1.1 on 2024-10-09 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_rename_expected_end_time_schedule_missed_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='schedule_time',
            new_name='scheduled_time',
        ),
    ]
