# Generated by Django 5.1.1 on 2024-10-11 04:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_rename_schedule_time_schedule_scheduled_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='scheduled_time',
            new_name='next_dose_due_at',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='next_dose_schedule',
        ),
        migrations.AddField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
